context = new AudioContext()
var Carrier = new OscillatorNode(context)
var ModulatorOsc = new OscillatorNode(context,{frequency:100,type:'square'})
var Modulator = context.createGain()
var AM = context.createGain()
Carrier.start()
ModulatorOsc.start()
ModulatorOsc.connect(Modulator)
Modulator.connect(AM.gain)
Carrier.connect(AM)
AM.connect(context.destination)
